columnSuffix: null
handle: timeline
instructions: null
name: Tijdslijn
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Jaar
            -
              - handle
              - year
            -
              - width
              - ''
            -
              - type
              - number
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Titel
            -
              - handle
              - title
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - Tekst
            -
              - handle
              - text
            -
              - width
              - ''
            -
              - type
              - multiline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
        -
          - col3
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
